project:
  type: website
  output-dir: /Users/awesometyler/John-Bow

website:
  title: "John Pikachu"
  navbar:
    left:
      - href: index.qmd
        text: Template1
      - href: Template2.html
        text: Template2
      - href: Template3.qmd
        text: Template3


format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

